import { DealType } from "@prisma/client";
import { DealStatus } from "@prisma/client";


export const sampleDeals = [
  {
    brokerage: "BizBroker Inc.",
    firstName: "Alice",
    lastName: "Smith",
    tags: ["technology", "SaaS"],
    email: "alice.smith@example.com",
    linkedinUrl: "https://linkedin.com/in/alicesmith",
    workPhone: "+1-555-123-4567",
    dealCaption: "Profitable SaaS business for sale",
    revenue: 1500000,
    ebitda: 350000,
    title: "SaaS Platform Acquisition Opportunity",
    dealTeaser: "Cloud-based SaaS platform with recurring revenue.",
    grossRevenue: 1600000,
    askingPrice: 2500000,
    ebitdaMargin: 23.3,
    industry: "Technology",
    dealType: DealType.MANUAL,
    sourceWebsite: "https://bizbroker.com/listing/saas-platform",
    companyLocation: "San Francisco, CA",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: false,
    isPublished: false,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "HealthDeals",
    firstName: "Bob",
    lastName: "Johnson",
    tags: ["healthcare", "clinic"],
    email: "bob.johnson@healthdeals.com",
    linkedinUrl: "https://linkedin.com/in/bobjohnson",
    workPhone: "+1-555-987-6543",
    dealCaption: "Multi-location urgent care clinics",
    revenue: 3200000,
    ebitda: 800000,
    title: "Urgent Care Clinics Portfolio",
    dealTeaser: "Growing network of urgent care clinics in the Midwest.",
    grossRevenue: 3400000,
    askingPrice: 4200000,
    ebitdaMargin: 25.0,
    industry: "Healthcare",
    dealType: DealType.MANUAL,
    sourceWebsite: "https://healthdeals.com/listing/urgent-care",
    companyLocation: "Chicago, IL",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: true,
    isPublished: true,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "RetailBiz",
    firstName: "Carol",
    lastName: "Lee",
    tags: ["retail", "franchise"],
    email: "carol.lee@retailbiz.com",
    linkedinUrl: "https://linkedin.com/in/carollee",
    workPhone: "+1-555-222-3333",
    dealCaption: "National Retail Franchise",
    revenue: 5000000,
    ebitda: 1200000,
    title: "Retail Franchise Expansion",
    dealTeaser: "Well-known retail franchise with national presence.",
    grossRevenue: 5200000,
    askingPrice: 7000000,
    ebitdaMargin: 24.0,
    industry: "Retail",
    dealType: DealType.SCRAPED,
    sourceWebsite: "https://retailbiz.com/listing/franchise",
    companyLocation: "Dallas, TX",
    bitrixLink: "",
    status: DealStatus.UNDER_CONTRACT,
    isReviewed: false,
    isPublished: false,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "FinServe",
    firstName: "David",
    lastName: "Nguyen",
    tags: ["finance", "consulting"],
    email: "david.nguyen@finserve.com",
    linkedinUrl: "https://linkedin.com/in/davidnguyen",
    workPhone: "+1-555-444-5555",
    dealCaption: "Financial Consulting Firm",
    revenue: 2000000,
    ebitda: 500000,
    title: "Consulting Firm for Sale",
    dealTeaser: "Established financial consulting firm with strong client base.",
    grossRevenue: 2100000,
    askingPrice: 3000000,
    ebitdaMargin: 25.0,
    industry: "Finance",
    dealType: DealType.AI_INFERRED,
    sourceWebsite: "https://finserve.com/listing/consulting-firm",
    companyLocation: "Boston, MA",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: true,
    isPublished: false,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "MedTech Brokers",
    firstName: "Eva",
    lastName: "Martinez",
    tags: ["medical", "devices"],
    email: "eva.martinez@medtech.com",
    linkedinUrl: "https://linkedin.com/in/evamartinez",
    workPhone: "+1-555-666-7777",
    dealCaption: "Medical Device Manufacturer",
    revenue: 8000000,
    ebitda: 2000000,
    title: "Medical Device Company for Acquisition",
    dealTeaser: "Innovative medical device manufacturer with global sales.",
    grossRevenue: 8200000,
    askingPrice: 12000000,
    ebitdaMargin: 25.0,
    industry: "Medical Devices",
    dealType: DealType.MANUAL,
    sourceWebsite: "https://medtech.com/listing/device-manufacturer",
    companyLocation: "Minneapolis, MN",
    bitrixLink: "",
    status: DealStatus.SOLD,
    isReviewed: true,
    isPublished: true,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "Manufacturing Plus",
    firstName: "Frank",
    lastName: "Wilson",
    tags: ["manufacturing", "automotive"],
    email: "frank.wilson@mfgplus.com",
    linkedinUrl: "https://linkedin.com/in/frankwilson",
    workPhone: "+1-555-888-9999",
    dealCaption: "Automotive Parts Manufacturing",
    revenue: 12000000,
    ebitda: 2800000,
    title: "Auto Parts Manufacturer",
    dealTeaser: "Established automotive parts manufacturer serving OEMs.",
    grossRevenue: 12500000,
    askingPrice: 18000000,
    ebitdaMargin: 23.3,
    industry: "Manufacturing",
    dealType: DealType.SCRAPED,
    sourceWebsite: "https://mfgplus.com/listing/auto-parts",
    companyLocation: "Detroit, MI",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: true,
    isPublished: true,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "Restaurant Partners",
    firstName: "Grace",
    lastName: "Chen",
    tags: ["restaurant", "hospitality"],
    email: "grace.chen@restpartners.com",
    linkedinUrl: "https://linkedin.com/in/gracechen",
    workPhone: "+1-555-111-2222",
    dealCaption: "Fine Dining Restaurant Chain",
    revenue: 4500000,
    ebitda: 900000,
    title: "Upscale Restaurant Portfolio",
    dealTeaser: "Premium restaurant chain with award-winning chefs.",
    grossRevenue: 4700000,
    askingPrice: 6500000,
    ebitdaMargin: 20.0,
    industry: "Hospitality",
    dealType: DealType.MANUAL,
    sourceWebsite: "https://restpartners.com/listing/fine-dining",
    companyLocation: "New York, NY",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: false,
    isPublished: false,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "Tech Ventures",
    firstName: "Henry",
    lastName: "Davis",
    tags: ["software", "AI"],
    email: "henry.davis@techventures.com",
    linkedinUrl: "https://linkedin.com/in/henrydavis",
    workPhone: "+1-555-333-4444",
    dealCaption: "AI-Powered Analytics Platform",
    revenue: 2800000,
    ebitda: 700000,
    title: "AI Analytics Software Company",
    dealTeaser: "Cutting-edge AI analytics platform for enterprise clients.",
    grossRevenue: 2950000,
    askingPrice: 4200000,
    ebitdaMargin: 25.0,
    industry: "Technology",
    dealType: DealType.AI_INFERRED,
    sourceWebsite: "https://techventures.com/listing/ai-analytics",
    companyLocation: "Seattle, WA",
    bitrixLink: "",
    status: DealStatus.UNDER_CONTRACT,
    isReviewed: true,
    isPublished: true,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "Construction Deals",
    firstName: "Isabella",
    lastName: "Rodriguez",
    tags: ["construction", "commercial"],
    email: "isabella.rodriguez@constructiondeals.com",
    linkedinUrl: "https://linkedin.com/in/isabellarodriguez",
    workPhone: "+1-555-555-6666",
    dealCaption: "Commercial Construction Company",
    revenue: 15000000,
    ebitda: 3500000,
    title: "Established Construction Firm",
    dealTeaser: "Leading commercial construction company with major contracts.",
    grossRevenue: 15800000,
    askingPrice: 22000000,
    ebitdaMargin: 23.3,
    industry: "Construction",
    dealType: DealType.MANUAL,
    sourceWebsite: "https://constructiondeals.com/listing/commercial",
    companyLocation: "Phoenix, AZ",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: true,
    isPublished: false,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "E-commerce Hub",
    firstName: "Jack",
    lastName: "Thompson",
    tags: ["ecommerce", "digital"],
    email: "jack.thompson@ecommercehub.com",
    linkedinUrl: "https://linkedin.com/in/jackthompson",
    workPhone: "+1-555-777-8888",
    dealCaption: "Multi-Brand E-commerce Portfolio",
    revenue: 6000000,
    ebitda: 1500000,
    title: "E-commerce Brand Collection",
    dealTeaser: "Diversified portfolio of successful e-commerce brands.",
    grossRevenue: 6300000,
    askingPrice: 9000000,
    ebitdaMargin: 25.0,
    industry: "E-commerce",
    dealType: DealType.SCRAPED,
    sourceWebsite: "https://ecommercehub.com/listing/brands",
    companyLocation: "Austin, TX",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: false,
    isPublished: true,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "Energy Solutions",
    firstName: "Karen",
    lastName: "White",
    tags: ["energy", "renewable"],
    email: "karen.white@energysolutions.com",
    linkedinUrl: "https://linkedin.com/in/karenwhite",
    workPhone: "+1-555-999-1111",
    dealCaption: "Solar Installation Company",
    revenue: 7500000,
    ebitda: 1800000,
    title: "Solar Energy Installation Business",
    dealTeaser: "Fast-growing solar installation company with residential focus.",
    grossRevenue: 7800000,
    askingPrice: 11000000,
    ebitdaMargin: 24.0,
    industry: "Energy",
    dealType: DealType.AI_INFERRED,
    sourceWebsite: "https://energysolutions.com/listing/solar",
    companyLocation: "Denver, CO",
    bitrixLink: "",
    status: DealStatus.SOLD,
    isReviewed: true,
    isPublished: true,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "Logistics Pro",
    firstName: "Liam",
    lastName: "Brown",
    tags: ["logistics", "transportation"],
    email: "liam.brown@logisticspro.com",
    linkedinUrl: "https://linkedin.com/in/liambrown",
    workPhone: "+1-555-222-5555",
    dealCaption: "Regional Transportation Company",
    revenue: 9500000,
    ebitda: 2200000,
    title: "Transportation and Logistics Firm",
    dealTeaser: "Regional leader in freight transportation and logistics.",
    grossRevenue: 9900000,
    askingPrice: 14500000,
    ebitdaMargin: 23.2,
    industry: "Logistics",
    dealType: DealType.MANUAL,
    sourceWebsite: "https://logisticspro.com/listing/transportation",
    companyLocation: "Atlanta, GA",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: true,
    isPublished: false,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "Pet Business Brokers",
    firstName: "Maya",
    lastName: "Patel",
    tags: ["pet", "retail"],
    email: "maya.patel@petbizbrokers.com",
    linkedinUrl: "https://linkedin.com/in/mayapatel",
    workPhone: "+1-555-444-7777",
    dealCaption: "Pet Supply Chain",
    revenue: 3800000,
    ebitda: 950000,
    title: "Pet Retail Chain Acquisition",
    dealTeaser: "Growing pet supply store chain with loyal customer base.",
    grossRevenue: 4000000,
    askingPrice: 5800000,
    ebitdaMargin: 25.0,
    industry: "Retail",
    dealType: DealType.SCRAPED,
    sourceWebsite: "https://petbizbrokers.com/listing/supply-chain",
    companyLocation: "Portland, OR",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: false,
    isPublished: true,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "Beauty Business Sales",
    firstName: "Noah",
    lastName: "Kim",
    tags: ["beauty", "franchise"],
    email: "noah.kim@beautybiz.com",
    linkedinUrl: "https://linkedin.com/in/noahkim",
    workPhone: "+1-555-666-9999",
    dealCaption: "Beauty Salon Franchise",
    revenue: 2200000,
    ebitda: 550000,
    title: "Multi-Location Beauty Salon",
    dealTeaser: "Established beauty salon franchise with premium services.",
    grossRevenue: 2350000,
    askingPrice: 3300000,
    ebitdaMargin: 25.0,
    industry: "Beauty",
    dealType: DealType.MANUAL,
    sourceWebsite: "https://beautybiz.com/listing/salon-franchise",
    companyLocation: "Miami, FL",
    bitrixLink: "",
    status: DealStatus.UNDER_CONTRACT,
    isReviewed: true,
    isPublished: true,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "Food Service Partners",
    firstName: "Olivia",
    lastName: "Garcia",
    tags: ["food", "catering"],
    email: "olivia.garcia@foodservice.com",
    linkedinUrl: "https://linkedin.com/in/oliviagarcia",
    workPhone: "+1-555-888-3333",
    dealCaption: "Corporate Catering Business",
    revenue: 4200000,
    ebitda: 1050000,
    title: "Corporate Catering Company",
    dealTeaser: "Premium corporate catering service with Fortune 500 clients.",
    grossRevenue: 4400000,
    askingPrice: 6300000,
    ebitdaMargin: 25.0,
    industry: "Food Service",
    dealType: DealType.AI_INFERRED,
    sourceWebsite: "https://foodservice.com/listing/catering",
    companyLocation: "Los Angeles, CA",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: false,
    isPublished: false,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "Security Solutions",
    firstName: "Paul",
    lastName: "Anderson",
    tags: ["security", "technology"],
    email: "paul.anderson@securitysolutions.com",
    linkedinUrl: "https://linkedin.com/in/paulanderson",
    workPhone: "+1-555-111-5555",
    dealCaption: "Cybersecurity Consulting Firm",
    revenue: 3500000,
    ebitda: 875000,
    title: "Cybersecurity Services Company",
    dealTeaser: "Leading cybersecurity consulting firm with enterprise clients.",
    grossRevenue: 3650000,
    askingPrice: 5250000,
    ebitdaMargin: 25.0,
    industry: "Technology",
    dealType: DealType.MANUAL,
    sourceWebsite: "https://securitysolutions.com/listing/cybersecurity",
    companyLocation: "Washington, DC",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: true,
    isPublished: true,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "Fitness Business Brokers",
    firstName: "Quinn",
    lastName: "Taylor",
    tags: ["fitness", "wellness"],
    email: "quinn.taylor@fitnessbiz.com",
    linkedinUrl: "https://linkedin.com/in/quinntaylor",
    workPhone: "+1-555-333-7777",
    dealCaption: "Boutique Fitness Studio Chain",
    revenue: 1800000,
    ebitda: 450000,
    title: "Boutique Fitness Studios",
    dealTeaser: "Trendy boutique fitness studios with premium memberships.",
    grossRevenue: 1900000,
    askingPrice: 2700000,
    ebitdaMargin: 25.0,
    industry: "Fitness",
    dealType: DealType.SCRAPED,
    sourceWebsite: "https://fitnessbiz.com/listing/boutique-studios",
    companyLocation: "San Diego, CA",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: false,
    isPublished: true,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "Education Partners",
    firstName: "Rachel",
    lastName: "Miller",
    tags: ["education", "training"],
    email: "rachel.miller@edupartners.com",
    linkedinUrl: "https://linkedin.com/in/rachelmiller",
    workPhone: "+1-555-555-9999",
    dealCaption: "Professional Training Company",
    revenue: 2600000,
    ebitda: 650000,
    title: "Corporate Training Business",
    dealTeaser: "Established professional training company serving enterprises.",
    grossRevenue: 2750000,
    askingPrice: 3900000,
    ebitdaMargin: 25.0,
    industry: "Education",
    dealType: DealType.AI_INFERRED,
    sourceWebsite: "https://edupartners.com/listing/training",
    companyLocation: "Nashville, TN",
    bitrixLink: "",
    status: DealStatus.SOLD,
    isReviewed: true,
    isPublished: true,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "Digital Marketing Pro",
    firstName: "Sam",
    lastName: "Wilson",
    tags: ["marketing", "digital"],
    email: "sam.wilson@digitalmarketing.com",
    linkedinUrl: "https://linkedin.com/in/samwilson",
    workPhone: "+1-555-777-2222",
    dealCaption: "Full-Service Digital Marketing Agency",
    revenue: 4800000,
    ebitda: 1200000,
    title: "Digital Marketing Agency",
    dealTeaser: "Award-winning digital marketing agency with blue-chip clients.",
    grossRevenue: 5000000,
    askingPrice: 7200000,
    ebitdaMargin: 25.0,
    industry: "Marketing",
    dealType: DealType.MANUAL,
    sourceWebsite: "https://digitalmarketing.com/listing/agency",
    companyLocation: "Charlotte, NC",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: true,
    isPublished: false,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "Agricultural Ventures",
    firstName: "Tina",
    lastName: "Johnson",
    tags: ["agriculture", "farming"],
    email: "tina.johnson@agriventures.com",
    linkedinUrl: "https://linkedin.com/in/tinajohnson",
    workPhone: "+1-555-999-4444",
    dealCaption: "Organic Farm Operation",
    revenue: 3200000,
    ebitda: 800000,
    title: "Organic Farming Business",
    dealTeaser: "Certified organic farm with direct-to-consumer sales.",
    grossRevenue: 3350000,
    askingPrice: 4800000,
    ebitdaMargin: 25.0,
    industry: "Agriculture",
    dealType: DealType.SCRAPED,
    sourceWebsite: "https://agriventures.com/listing/organic-farm",
    companyLocation: "Des Moines, IA",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: false,
    isPublished: true,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "Real Estate Pros",
    firstName: "Victor",
    lastName: "Lee",
    tags: ["real estate", "property"],
    email: "victor.lee@realestatepros.com",
    linkedinUrl: "https://linkedin.com/in/victorlee",
    workPhone: "+1-555-222-6666",
    dealCaption: "Property Management Company",
    revenue: 5500000,
    ebitda: 1375000,
    title: "Multi-Family Property Management",
    dealTeaser: "Leading property management firm with 2,000+ units.",
    grossRevenue: 5750000,
    askingPrice: 8250000,
    ebitdaMargin: 25.0,
    industry: "Real Estate",
    dealType: DealType.MANUAL,
    sourceWebsite: "https://realestatepos.com/listing/property-mgmt",
    companyLocation: "Orlando, FL",
    bitrixLink: "",
    status: DealStatus.UNDER_CONTRACT,
    isReviewed: true,
    isPublished: true,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "Travel & Tourism",
    firstName: "Wendy",
    lastName: "Chen",
    tags: ["travel", "tourism"],
    email: "wendy.chen@traveltourism.com",
    linkedinUrl: "https://linkedin.com/in/wendychen",
    workPhone: "+1-555-444-8888",
    dealCaption: "Adventure Travel Company",
    revenue: 2800000,
    ebitda: 700000,
    title: "Adventure Tourism Business",
    dealTeaser: "Premium adventure travel company with international tours.",
    grossRevenue: 2950000,
    askingPrice: 4200000,
    ebitdaMargin: 25.0,
    industry: "Tourism",
    dealType: DealType.AI_INFERRED,
    sourceWebsite: "https://traveltourism.com/listing/adventure",
    companyLocation: "Salt Lake City, UT",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: false,
    isPublished: false,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "Insurance Partners",
    firstName: "Xavier",
    lastName: "Rodriguez",
    tags: ["insurance", "financial"],
    email: "xavier.rodriguez@insurancepartners.com",
    linkedinUrl: "https://linkedin.com/in/xavierrodriguez",
    workPhone: "+1-555-666-1111",
    dealCaption: "Independent Insurance Agency",
    revenue: 1900000,
    ebitda: 475000,
    title: "Multi-Line Insurance Agency",
    dealTeaser: "Well-established insurance agency with diverse client base.",
    grossRevenue: 2000000,
    askingPrice: 2850000,
    ebitdaMargin: 25.0,
    industry: "Insurance",
    dealType: DealType.SCRAPED,
    sourceWebsite: "https://insurancepartners.com/listing/agency",
    companyLocation: "Richmond, VA",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: true,
    isPublished: true,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "Automotive Dealers",
    firstName: "Yolanda",
    lastName: "Smith",
    tags: ["automotive", "dealership"],
    email: "yolanda.smith@autodealers.com",
    linkedinUrl: "https://linkedin.com/in/yolandasmith",
    workPhone: "+1-555-888-5555",
    dealCaption: "Used Car Dealership Group",
    revenue: 18000000,
    ebitda: 4200000,
    title: "Multi-Location Auto Dealership",
    dealTeaser: "Profitable used car dealership with multiple locations.",
    grossRevenue: 18800000,
    askingPrice: 27000000,
    ebitdaMargin: 23.3,
    industry: "Automotive",
    dealType: DealType.MANUAL,
    sourceWebsite: "https://autodealers.com/listing/dealership",
    companyLocation: "Houston, TX",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: true,
    isPublished: false,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "Legal Services",
    firstName: "Zoe",
    lastName: "Martinez",
    tags: ["legal", "services"],
    email: "zoe.martinez@legalservices.com",
    linkedinUrl: "https://linkedin.com/in/zoemartinez",
    workPhone: "+1-555-111-3333",
    dealCaption: "Personal Injury Law Firm",
    revenue: 6500000,
    ebitda: 1625000,
    title: "Established Law Firm",
    dealTeaser: "Top personal injury law firm with strong case history.",
    grossRevenue: 6800000,
    askingPrice: 9750000,
    ebitdaMargin: 25.0,
    industry: "Legal",
    dealType: DealType.AI_INFERRED,
    sourceWebsite: "https://legalservices.com/listing/law-firm",
    companyLocation: "Tampa, FL",
    bitrixLink: "",
    status: DealStatus.SOLD,
    isReviewed: true,
    isPublished: true,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "Pharmacy Partners",
    firstName: "Aaron",
    lastName: "Davis",
    tags: ["pharmacy", "healthcare"],
    email: "aaron.davis@pharmacypartners.com",
    linkedinUrl: "https://linkedin.com/in/aarondavis",
    workPhone: "+1-555-333-9999",
    dealCaption: "Independent Pharmacy Chain",
    revenue: 8500000,
    ebitda: 2125000,
    title: "Multi-Location Pharmacy",
    dealTeaser: "Independent pharmacy chain with specialty services.",
    grossRevenue: 8900000,
    askingPrice: 12750000,
    ebitdaMargin: 25.0,
    industry: "Healthcare",
    dealType: DealType.MANUAL,
    sourceWebsite: "https://pharmacypartners.com/listing/chain",
    companyLocation: "Cleveland, OH",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: false,
    isPublished: true,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "Alpha Brokers",
    firstName: "Frank",
    lastName: "Miller",
    tags: ["logistics", "transport"],
    email: "frank.miller@alphabrokers.com",
    linkedinUrl: "https://linkedin.com/in/frankmiller",
    workPhone: "+1-555-101-2020",
    dealCaption: "Regional Logistics Company",
    revenue: 2200000,
    ebitda: 400000,
    title: "Logistics Company for Sale",
    dealTeaser: "Efficient logistics provider with regional contracts.",
    grossRevenue: 2300000,
    askingPrice: 3200000,
    ebitdaMargin: 18.2,
    industry: "Logistics",
    dealType: DealType.MANUAL,
    sourceWebsite: "https://alphabrokers.com/listing/logistics",
    companyLocation: "Atlanta, GA",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: false,
    isPublished: false,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "EduVentures",
    firstName: "Grace",
    lastName: "Kim",
    tags: ["education", "online"],
    email: "grace.kim@eduventures.com",
    linkedinUrl: "https://linkedin.com/in/gracekim",
    workPhone: "+1-555-303-4040",
    dealCaption: "Online Learning Platform",
    revenue: 1800000,
    ebitda: 350000,
    title: "EdTech Platform Acquisition",
    dealTeaser: "Popular online learning platform with 50k users.",
    grossRevenue: 1850000,
    askingPrice: 2700000,
    ebitdaMargin: 19.4,
    industry: "Education",
    dealType: DealType.SCRAPED,
    sourceWebsite: "https://eduventures.com/listing/edtech",
    companyLocation: "Seattle, WA",
    bitrixLink: "",
    status: DealStatus.UNDER_CONTRACT,
    isReviewed: true,
    isPublished: false,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "GreenEnergy Partners",
    firstName: "Henry",
    lastName: "Lopez",
    tags: ["energy", "renewable"],
    email: "henry.lopez@greenenergy.com",
    linkedinUrl: "https://linkedin.com/in/henrylopez",
    workPhone: "+1-555-505-6060",
    dealCaption: "Solar Energy Installations",
    revenue: 4000000,
    ebitda: 900000,
    title: "Solar Energy Business for Sale",
    dealTeaser: "Profitable solar installation company with government contracts.",
    grossRevenue: 4100000,
    askingPrice: 6000000,
    ebitdaMargin: 22.0,
    industry: "Energy",
    dealType: DealType.AI_INFERRED,
    sourceWebsite: "https://greenenergy.com/listing/solar",
    companyLocation: "Phoenix, AZ",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: false,
    isPublished: true,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "RetailBiz",
    firstName: "Ivy",
    lastName: "Chen",
    tags: ["retail", "fashion"],
    email: "ivy.chen@retailbiz.com",
    linkedinUrl: "https://linkedin.com/in/ivychen",
    workPhone: "+1-555-707-8080",
    dealCaption: "Fashion Retail Chain",
    revenue: 3500000,
    ebitda: 700000,
    title: "Fashion Retail Chain for Acquisition",
    dealTeaser: "Multi-location fashion retailer with strong brand.",
    grossRevenue: 3600000,
    askingPrice: 5000000,
    ebitdaMargin: 20.0,
    industry: "Retail",
    dealType: DealType.MANUAL,
    sourceWebsite: "https://retailbiz.com/listing/fashion",
    companyLocation: "Los Angeles, CA",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: true,
    isPublished: false,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "MedTech Brokers",
    firstName: "Jack",
    lastName: "Davis",
    tags: ["medical", "diagnostics"],
    email: "jack.davis@medtech.com",
    linkedinUrl: "https://linkedin.com/in/jackdavis",
    workPhone: "+1-555-909-1010",
    dealCaption: "Diagnostic Equipment Manufacturer",
    revenue: 6000000,
    ebitda: 1500000,
    title: "Diagnostic Equipment Company for Sale",
    dealTeaser: "Leading diagnostic equipment manufacturer with global reach.",
    grossRevenue: 6100000,
    askingPrice: 9000000,
    ebitdaMargin: 24.6,
    industry: "Medical Devices",
    dealType: DealType.SCRAPED,
    sourceWebsite: "https://medtech.com/listing/diagnostics",
    companyLocation: "Houston, TX",
    bitrixLink: "",
    status: DealStatus.UNDER_CONTRACT,
    isReviewed: false,
    isPublished: true,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "BizBroker Inc.",
    firstName: "Karen",
    lastName: "White",
    tags: ["technology", "AI"],
    email: "karen.white@bizbroker.com",
    linkedinUrl: "https://linkedin.com/in/karenwhite",
    workPhone: "+1-555-111-2222",
    dealCaption: "AI SaaS Startup",
    revenue: 1200000,
    ebitda: 250000,
    title: "AI SaaS Startup for Sale",
    dealTeaser: "AI-powered SaaS platform with rapid growth.",
    grossRevenue: 1250000,
    askingPrice: 2000000,
    ebitdaMargin: 20.8,
    industry: "Technology",
    dealType: DealType.AI_INFERRED,
    sourceWebsite: "https://bizbroker.com/listing/ai-saas",
    companyLocation: "San Jose, CA",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: true,
    isPublished: false,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "HealthDeals",
    firstName: "Liam",
    lastName: "Patel",
    tags: ["healthcare", "practice"],
    email: "liam.patel@healthdeals.com",
    linkedinUrl: "https://linkedin.com/in/liampatel",
    workPhone: "+1-555-333-4444",
    dealCaption: "Specialty Medical Practice",
    revenue: 2500000,
    ebitda: 600000,
    title: "Specialty Medical Practice for Sale",
    dealTeaser: "Established specialty practice with loyal patient base.",
    grossRevenue: 2550000,
    askingPrice: 3500000,
    ebitdaMargin: 24.0,
    industry: "Healthcare",
    dealType: DealType.MANUAL,
    sourceWebsite: "https://healthdeals.com/listing/specialty-practice",
    companyLocation: "Philadelphia, PA",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: false,
    isPublished: true,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "FinServe",
    firstName: "Mona",
    lastName: "Singh",
    tags: ["finance", "insurance"],
    email: "mona.singh@finserve.com",
    linkedinUrl: "https://linkedin.com/in/monasingh",
    workPhone: "+1-555-555-6666",
    dealCaption: "Insurance Brokerage",
    revenue: 3000000,
    ebitda: 700000,
    title: "Insurance Brokerage for Acquisition",
    dealTeaser: "Profitable insurance brokerage with recurring revenue.",
    grossRevenue: 3100000,
    askingPrice: 4200000,
    ebitdaMargin: 23.3,
    industry: "Finance",
    dealType: DealType.SCRAPED,
    sourceWebsite: "https://finserve.com/listing/insurance",
    companyLocation: "Charlotte, NC",
    bitrixLink: "",
    status: DealStatus.UNDER_CONTRACT,
    isReviewed: true,
    isPublished: false,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "Alpha Brokers",
    firstName: "Nina",
    lastName: "Brown",
    tags: ["logistics", "supply chain"],
    email: "nina.brown@alphabrokers.com",
    linkedinUrl: "https://linkedin.com/in/ninabrown",
    workPhone: "+1-555-777-8888",
    dealCaption: "Supply Chain Solutions Provider",
    revenue: 2700000,
    ebitda: 500000,
    title: "Supply Chain Company for Sale",
    dealTeaser: "Innovative supply chain solutions with national clients.",
    grossRevenue: 2750000,
    askingPrice: 3700000,
    ebitdaMargin: 18.5,
    industry: "Logistics",
    dealType: DealType.AI_INFERRED,
    sourceWebsite: "https://alphabrokers.com/listing/supply-chain",
    companyLocation: "Columbus, OH",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: false,
    isPublished: true,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "EduVentures",
    firstName: "Oscar",
    lastName: "Garcia",
    tags: ["education", "K12"],
    email: "oscar.garcia@eduventures.com",
    linkedinUrl: "https://linkedin.com/in/oscargarcia",
    workPhone: "+1-555-999-0000",
    dealCaption: "K-12 Tutoring Centers",
    revenue: 1600000,
    ebitda: 300000,
    title: "Tutoring Centers for Sale",
    dealTeaser: "Network of K-12 tutoring centers with strong reputation.",
    grossRevenue: 1650000,
    askingPrice: 2200000,
    ebitdaMargin: 18.2,
    industry: "Education",
    dealType: DealType.MANUAL,
    sourceWebsite: "https://eduventures.com/listing/tutoring",
    companyLocation: "Orlando, FL",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: true,
    isPublished: false,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "GreenEnergy Partners",
    firstName: "Paul",
    lastName: "Nguyen",
    tags: ["energy", "wind"],
    email: "paul.nguyen@greenenergy.com",
    linkedinUrl: "https://linkedin.com/in/paulnguyen",
    workPhone: "+1-555-121-2323",
    dealCaption: "Wind Farm Operator",
    revenue: 5000000,
    ebitda: 1200000,
    title: "Wind Farm for Acquisition",
    dealTeaser: "Profitable wind farm operator with long-term contracts.",
    grossRevenue: 5100000,
    askingPrice: 8000000,
    ebitdaMargin: 24.0,
    industry: "Energy",
    dealType: DealType.SCRAPED,
    sourceWebsite: "https://greenenergy.com/listing/wind",
    companyLocation: "Des Moines, IA",
    bitrixLink: "",
    status: DealStatus.UNDER_CONTRACT,
    isReviewed: false,
    isPublished: true,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "RetailBiz",
    firstName: "Quinn",
    lastName: "Evans",
    tags: ["retail", "grocery"],
    email: "quinn.evans@retailbiz.com",
    linkedinUrl: "https://linkedin.com/in/quinnevans",
    workPhone: "+1-555-343-4545",
    dealCaption: "Regional Grocery Chain",
    revenue: 4200000,
    ebitda: 900000,
    title: "Grocery Chain for Sale",
    dealTeaser: "Established grocery chain with loyal customer base.",
    grossRevenue: 4300000,
    askingPrice: 6000000,
    ebitdaMargin: 20.9,
    industry: "Retail",
    dealType: DealType.AI_INFERRED,
    sourceWebsite: "https://retailbiz.com/listing/grocery",
    companyLocation: "Kansas City, MO",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: true,
    isPublished: false,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "MedTech Brokers",
    firstName: "Rita",
    lastName: "Sharma",
    tags: ["medical", "software"],
    email: "rita.sharma@medtech.com",
    linkedinUrl: "https://linkedin.com/in/ritasharma",
    workPhone: "+1-555-565-6767",
    dealCaption: "Healthcare Software Provider",
    revenue: 2100000,
    ebitda: 450000,
    title: "Healthcare Software Company for Sale",
    dealTeaser: "Healthcare SaaS provider with hospital clients.",
    grossRevenue: 2150000,
    askingPrice: 3200000,
    ebitdaMargin: 21.4,
    industry: "Medical Devices",
    dealType: DealType.MANUAL,
    sourceWebsite: "https://medtech.com/listing/software",
    companyLocation: "Salt Lake City, UT",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: false,
    isPublished: true,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "BizBroker Inc.",
    firstName: "Sam",
    lastName: "Wilson",
    tags: ["technology", "cloud"],
    email: "sam.wilson@bizbroker.com",
    linkedinUrl: "https://linkedin.com/in/samwilson",
    workPhone: "+1-555-787-8989",
    dealCaption: "Cloud Services Provider",
    revenue: 2600000,
    ebitda: 600000,
    title: "Cloud Services Company for Sale",
    dealTeaser: "Cloud infrastructure provider with enterprise clients.",
    grossRevenue: 2650000,
    askingPrice: 3800000,
    ebitdaMargin: 22.6,
    industry: "Technology",
    dealType: DealType.SCRAPED,
    sourceWebsite: "https://bizbroker.com/listing/cloud",
    companyLocation: "Denver, CO",
    bitrixLink: "",
    status: DealStatus.UNDER_CONTRACT,
    isReviewed: true,
    isPublished: false,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "HealthDeals",
    firstName: "Tina",
    lastName: "Young",
    tags: ["healthcare", "dental"],
    email: "tina.young@healthdeals.com",
    linkedinUrl: "https://linkedin.com/in/tinayoung",
    workPhone: "+1-555-909-1111",
    dealCaption: "Dental Practice Group",
    revenue: 1900000,
    ebitda: 400000,
    title: "Dental Practice Group for Sale",
    dealTeaser: "Multi-location dental practice with strong cash flow.",
    grossRevenue: 1950000,
    askingPrice: 2700000,
    ebitdaMargin: 21.1,
    industry: "Healthcare",
    dealType: DealType.AI_INFERRED,
    sourceWebsite: "https://healthdeals.com/listing/dental",
    companyLocation: "San Diego, CA",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: false,
    isPublished: true,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "FinServe",
    firstName: "Uma",
    lastName: "Zhang",
    tags: ["finance", "wealth"],
    email: "uma.zhang@finserve.com",
    linkedinUrl: "https://linkedin.com/in/umazhang",
    workPhone: "+1-555-121-3131",
    dealCaption: "Wealth Management Firm",
    revenue: 3500000,
    ebitda: 800000,
    title: "Wealth Management Firm for Sale",
    dealTeaser: "Boutique wealth management firm with HNW clients.",
    grossRevenue: 3550000,
    askingPrice: 4800000,
    ebitdaMargin: 22.5,
    industry: "Finance",
    dealType: DealType.MANUAL,
    sourceWebsite: "https://finserve.com/listing/wealth",
    companyLocation: "New York, NY",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: true,
    isPublished: false,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "Alpha Brokers",
    firstName: "Victor",
    lastName: "King",
    tags: ["logistics", "fleet"],
    email: "victor.king@alphabrokers.com",
    linkedinUrl: "https://linkedin.com/in/victorking",
    workPhone: "+1-555-232-4343",
    dealCaption: "Fleet Management Company",
    revenue: 2800000,
    ebitda: 600000,
    title: "Fleet Management Company for Sale",
    dealTeaser: "Fleet management provider with proprietary tech.",
    grossRevenue: 2850000,
    askingPrice: 3900000,
    ebitdaMargin: 21.1,
    industry: "Logistics",
    dealType: DealType.SCRAPED,
    sourceWebsite: "https://alphabrokers.com/listing/fleet",
    companyLocation: "Indianapolis, IN",
    bitrixLink: "",
    status: DealStatus.UNDER_CONTRACT,
    isReviewed: false,
    isPublished: true,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "EduVentures",
    firstName: "Wendy",
    lastName: "Ng",
    tags: ["education", "test prep"],
    email: "wendy.ng@eduventures.com",
    linkedinUrl: "https://linkedin.com/in/wendyng",
    workPhone: "+1-555-343-5454",
    dealCaption: "Test Prep Franchise",
    revenue: 1400000,
    ebitda: 250000,
    title: "Test Prep Franchise for Sale",
    dealTeaser: "National test prep franchise with strong brand.",
    grossRevenue: 1450000,
    askingPrice: 2000000,
    ebitdaMargin: 17.2,
    industry: "Education",
    dealType: DealType.AI_INFERRED,
    sourceWebsite: "https://eduventures.com/listing/testprep",
    companyLocation: "Austin, TX",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: true,
    isPublished: false,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "GreenEnergy Partners",
    firstName: "Xavier",
    lastName: "Lee",
    tags: ["energy", "battery"],
    email: "xavier.lee@greenenergy.com",
    linkedinUrl: "https://linkedin.com/in/xavierlee",
    workPhone: "+1-555-565-7676",
    dealCaption: "Battery Storage Solutions",
    revenue: 3200000,
    ebitda: 700000,
    title: "Battery Storage Company for Sale",
    dealTeaser: "Battery storage provider with patented technology.",
    grossRevenue: 3250000,
    askingPrice: 4500000,
    ebitdaMargin: 21.5,
    industry: "Energy",
    dealType: DealType.MANUAL,
    sourceWebsite: "https://greenenergy.com/listing/battery",
    companyLocation: "Reno, NV",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: false,
    isPublished: true,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "RetailBiz",
    firstName: "Yara",
    lastName: "Ali",
    tags: ["retail", "electronics"],
    email: "yara.ali@retailbiz.com",
    linkedinUrl: "https://linkedin.com/in/yaraali",
    workPhone: "+1-555-787-9898",
    dealCaption: "Electronics Retailer",
    revenue: 3800000,
    ebitda: 800000,
    title: "Electronics Retailer for Sale",
    dealTeaser: "Regional electronics retailer with e-commerce presence.",
    grossRevenue: 3850000,
    askingPrice: 5200000,
    ebitdaMargin: 20.8,
    industry: "Retail",
    dealType: DealType.SCRAPED,
    sourceWebsite: "https://retailbiz.com/listing/electronics",
    companyLocation: "Portland, OR",
    bitrixLink: "",
    status: DealStatus.UNDER_CONTRACT,
    isReviewed: true,
    isPublished: false,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "MedTech Brokers",
    firstName: "Zane",
    lastName: "Morgan",
    tags: ["medical", "lab"],
    email: "zane.morgan@medtech.com",
    linkedinUrl: "https://linkedin.com/in/zanemorgan",
    workPhone: "+1-555-909-2121",
    dealCaption: "Medical Lab Operator",
    revenue: 2700000,
    ebitda: 600000,
    title: "Medical Lab for Sale",
    dealTeaser: "Accredited medical lab with hospital contracts.",
    grossRevenue: 2750000,
    askingPrice: 3700000,
    ebitdaMargin: 21.8,
    industry: "Medical Devices",
    dealType: DealType.AI_INFERRED,
    sourceWebsite: "https://medtech.com/listing/lab",
    companyLocation: "Cleveland, OH",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: false,
    isPublished: true,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "BizBroker Inc.",
    firstName: "Amy",
    lastName: "Clark",
    tags: ["technology", "hardware"],
    email: "amy.clark@bizbroker.com",
    linkedinUrl: "https://linkedin.com/in/amyclark",
    workPhone: "+1-555-232-3434",
    dealCaption: "Hardware Startup",
    revenue: 1700000,
    ebitda: 350000,
    title: "Hardware Startup for Sale",
    dealTeaser: "Innovative hardware startup with patented products.",
    grossRevenue: 1750000,
    askingPrice: 2400000,
    ebitdaMargin: 20.6,
    industry: "Technology",
    dealType: DealType.MANUAL,
    sourceWebsite: "https://bizbroker.com/listing/hardware",
    companyLocation: "San Francisco, CA",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: true,
    isPublished: false,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "HealthDeals",
    firstName: "Ben",
    lastName: "Foster",
    tags: ["healthcare", "rehab"],
    email: "ben.foster@healthdeals.com",
    linkedinUrl: "https://linkedin.com/in/benfoster",
    workPhone: "+1-555-454-5656",
    dealCaption: "Rehabilitation Center",
    revenue: 2100000,
    ebitda: 500000,
    title: "Rehabilitation Center for Sale",
    dealTeaser: "Accredited rehab center with high occupancy.",
    grossRevenue: 2150000,
    askingPrice: 3000000,
    ebitdaMargin: 23.3,
    industry: "Healthcare",
    dealType: DealType.SCRAPED,
    sourceWebsite: "https://healthdeals.com/listing/rehab",
    companyLocation: "Tampa, FL",
    bitrixLink: "",
    status: DealStatus.UNDER_CONTRACT,
    isReviewed: false,
    isPublished: true,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "FinServe",
    firstName: "Cara",
    lastName: "Reed",
    tags: ["finance", "accounting"],
    email: "cara.reed@finserve.com",
    linkedinUrl: "https://linkedin.com/in/carareed",
    workPhone: "+1-555-676-7878",
    dealCaption: "Accounting Firm",
    revenue: 2300000,
    ebitda: 550000,
    title: "Accounting Firm for Sale",
    dealTeaser: "Established accounting firm with business clients.",
    grossRevenue: 2350000,
    askingPrice: 3200000,
    ebitdaMargin: 23.4,
    industry: "Finance",
    dealType: DealType.AI_INFERRED,
    sourceWebsite: "https://finserve.com/listing/accounting",
    companyLocation: "Dallas, TX",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: true,
    isPublished: false,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "Alpha Brokers",
    firstName: "Derek",
    lastName: "Stone",
    tags: ["logistics", "shipping"],
    email: "derek.stone@alphabrokers.com",
    linkedinUrl: "https://linkedin.com/in/derekstone",
    workPhone: "+1-555-898-9090",
    dealCaption: "Shipping Company",
    revenue: 3100000,
    ebitda: 650000,
    title: "Shipping Company for Sale",
    dealTeaser: "Regional shipping company with modern fleet.",
    grossRevenue: 3150000,
    askingPrice: 4100000,
    ebitdaMargin: 21.0,
    industry: "Logistics",
    dealType: DealType.MANUAL,
    sourceWebsite: "https://alphabrokers.com/listing/shipping",
    companyLocation: "Savannah, GA",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: false,
    isPublished: true,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
];