import { DealType } from "@prisma/client";
import { DealStatus } from "@prisma/client";


export const sampleDeals = [
  {
    brokerage: "BizBroker Inc.",
    firstName: "Alice",
    lastName: "Smith",
    tags: ["technology", "SaaS"],
    email: "alice.smith@example.com",
    linkedinUrl: "https://linkedin.com/in/alicesmith",
    workPhone: "+1-555-123-4567",
    dealCaption: "Profitable SaaS business for sale",
    revenue: 1500000,
    ebitda: 350000,
    title: "SaaS Platform Acquisition Opportunity",
    dealTeaser: "Cloud-based SaaS platform with recurring revenue.",
    grossRevenue: 1600000,
    askingPrice: 2500000,
    ebitdaMargin: 23.3,
    industry: "Technology",
    dealType: DealType.MANUAL,
    sourceWebsite: "https://bizbroker.com/listing/saas-platform",
    companyLocation: "San Francisco, CA",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: false,
    isPublished: false,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "HealthDeals",
    firstName: "Bob",
    lastName: "Johnson",
    tags: ["healthcare", "clinic"],
    email: "bob.johnson@healthdeals.com",
    linkedinUrl: "https://linkedin.com/in/bobjohnson",
    workPhone: "+1-555-987-6543",
    dealCaption: "Multi-location urgent care clinics",
    revenue: 3200000,
    ebitda: 800000,
    title: "Urgent Care Clinics Portfolio",
    dealTeaser: "Growing network of urgent care clinics in the Midwest.",
    grossRevenue: 3400000,
    askingPrice: 4200000,
    ebitdaMargin: 25.0,
    industry: "Healthcare",
    dealType: DealType.MANUAL,
    sourceWebsite: "https://healthdeals.com/listing/urgent-care",
    companyLocation: "Chicago, IL",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: true,
    isPublished: true,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "RetailBiz",
    firstName: "Carol",
    lastName: "Lee",
    tags: ["retail", "franchise"],
    email: "carol.lee@retailbiz.com",
    linkedinUrl: "https://linkedin.com/in/carollee",
    workPhone: "+1-555-222-3333",
    dealCaption: "National Retail Franchise",
    revenue: 5000000,
    ebitda: 1200000,
    title: "Retail Franchise Expansion",
    dealTeaser: "Well-known retail franchise with national presence.",
    grossRevenue: 5200000,
    askingPrice: 7000000,
    ebitdaMargin: 24.0,
    industry: "Retail",
    dealType: DealType.SCRAPED,
    sourceWebsite: "https://retailbiz.com/listing/franchise",
    companyLocation: "Dallas, TX",
    bitrixLink: "",
    status: DealStatus.UNDER_CONTRACT,
    isReviewed: false,
    isPublished: false,
    seen: false,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "FinServe",
    firstName: "David",
    lastName: "Nguyen",
    tags: ["finance", "consulting"],
    email: "david.nguyen@finserve.com",
    linkedinUrl: "https://linkedin.com/in/davidnguyen",
    workPhone: "+1-555-444-5555",
    dealCaption: "Financial Consulting Firm",
    revenue: 2000000,
    ebitda: 500000,
    title: "Consulting Firm for Sale",
    dealTeaser: "Established financial consulting firm with strong client base.",
    grossRevenue: 2100000,
    askingPrice: 3000000,
    ebitdaMargin: 25.0,
    industry: "Finance",
    dealType: DealType.AI_INFERRED,
    sourceWebsite: "https://finserve.com/listing/consulting-firm",
    companyLocation: "Boston, MA",
    bitrixLink: "",
    status: DealStatus.AVAILABLE,
    isReviewed: true,
    isPublished: false,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
  {
    brokerage: "MedTech Brokers",
    firstName: "Eva",
    lastName: "Martinez",
    tags: ["medical", "devices"],
    email: "eva.martinez@medtech.com",
    linkedinUrl: "https://linkedin.com/in/evamartinez",
    workPhone: "+1-555-666-7777",
    dealCaption: "Medical Device Manufacturer",
    revenue: 8000000,
    ebitda: 2000000,
    title: "Medical Device Company for Acquisition",
    dealTeaser: "Innovative medical device manufacturer with global sales.",
    grossRevenue: 8200000,
    askingPrice: 12000000,
    ebitdaMargin: 25.0,
    industry: "Medical Devices",
    dealType: DealType.MANUAL,
    sourceWebsite: "https://medtech.com/listing/device-manufacturer",
    companyLocation: "Minneapolis, MN",
    bitrixLink: "",
    status: DealStatus.SOLD,
    isReviewed: true,
    isPublished: true,
    seen: true,
    bitrixId: "",
    bitrixCreatedAt: undefined,
  },
];